endOfLine: lf
# 在语句末尾是否打印分号
semi: false
# 指定每个缩进级别的空格数
tabWidth: 4
overrides:
  - files:
      - "*.md"
      - "*.markdown"
      - "*.yml"
      - "*.yaml"
    options:
      tabWidth: 2
  - files:
      - "*.bat"
      - "*.cmd"
      - "*.cs"
    options:
      endOfLine: crlf
